version: '3'

services:
  apache:
    build: ./php
    container_name: apache
    ports:
        - ${APACHE_PORT}:80
    volumes:
      - ../src:/var/www
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/scripts/

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
        - ${MYSQL_PORT}:3306

  psql:
    build: ./postgres
    container_name: psql
    volumes:
      - ./postgres/datadir:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}

    ports:
      - ${POSTGRES_PORT}:5432

